// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(Dblibrary))]
    [Migration("20250422102348_o")]
    partial class o
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Books", b =>
                {
                    b.Property<int>("BookCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookCode"), 1L, 1);

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("PointsPerWeek")
                        .HasColumnType("int");

                    b.HasKey("BookCode");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("DAL.CardRedemption", b =>
                {
                    b.Property<int>("QuestionCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionCode"), 1L, 1);

                    b.Property<DateTime>("DateOfQuestion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageCode")
                        .HasColumnType("int");

                    b.Property<int>("PointsDeducted")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("balance")
                        .HasColumnType("int");

                    b.Property<int>("booksBookCode")
                        .HasColumnType("int");

                    b.Property<int>("idPackage")
                        .HasColumnType("int");

                    b.Property<int>("idbooks")
                        .HasColumnType("int");

                    b.HasKey("QuestionCode");

                    b.HasIndex("PackageCode");

                    b.HasIndex("booksBookCode");

                    b.ToTable("CardRedemptions");
                });

            modelBuilder.Entity("DAL.Package", b =>
                {
                    b.Property<int>("PackageCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageCode"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointCount")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("PackageCode");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("DAL.SubscriptionCard", b =>
                {
                    b.Property<int>("PurchaseCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseCode"), 1L, 1);

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseCode");

                    b.ToTable("SubscriptionCards");
                });

            modelBuilder.Entity("DAL.Subscriptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int>("UserCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("PackageSubscriptionCard", b =>
                {
                    b.Property<int>("PackagesPackageCode")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionCardsPurchaseCode")
                        .HasColumnType("int");

                    b.HasKey("PackagesPackageCode", "SubscriptionCardsPurchaseCode");

                    b.HasIndex("SubscriptionCardsPurchaseCode");

                    b.ToTable("PackageSubscriptionCard");
                });

            modelBuilder.Entity("DAL.CardRedemption", b =>
                {
                    b.HasOne("DAL.Package", "Package")
                        .WithMany("CardRedemptions")
                        .HasForeignKey("PackageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Books", "books")
                        .WithMany("CardRedemptions")
                        .HasForeignKey("booksBookCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("books");
                });

            modelBuilder.Entity("PackageSubscriptionCard", b =>
                {
                    b.HasOne("DAL.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.SubscriptionCard", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionCardsPurchaseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Books", b =>
                {
                    b.Navigation("CardRedemptions");
                });

            modelBuilder.Entity("DAL.Package", b =>
                {
                    b.Navigation("CardRedemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
